Update github-action.yml

diff --git a/.github/workflows/github-action.yml b/.github/workflows/github-action.yml
--- a/.github/workflows/github-action.yml
+++ b/.github/workflows/github-action.yml
@@ -15,11 +15,12 @@ jobs:
       - run: pip install -r requirements.txt
       - run: pip install pytest pytest-cov pytest-mock
       - name: Test with pytest
-        run: pytest test_create_database.py --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
+        run: |
+          pytest test_create_database.py --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
+          ls
         working-directory: tests
-      - name: Archive code coverage results
-        uses: actions/upload-artifact@v4
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
         with:
-          name: my-artifact
-          path: tests/junit/test-results.xml
-          retention-days: 5
+          report_paths: '**/tests/junit/test-results.xml'
